// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuWEECJjbkIG0z1z7y6tKZTI7Tu-EZsHw',
    appId: '1:17657594896:web:c8ccce3b7c339b705ab695',
    messagingSenderId: '17657594896',
    projectId: 'dolce-legado',
    authDomain: 'dolce-legado.firebaseapp.com',
    storageBucket: 'dolce-legado.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ8GpEXCieyM3u215mFJeJSsTSomzrwGQ',
    appId: '1:17657594896:ios:35069fa089c0bcc35ab695',
    messagingSenderId: '17657594896',
    projectId: 'dolce-legado',
    storageBucket: 'dolce-legado.firebasestorage.app',
    iosBundleId: 'com.example.dolceLegado',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuWEECJjbkIG0z1z7y6tKZTI7Tu-EZsHw',
    appId: '1:17657594896:web:5123c16d90ba57435ab695',
    messagingSenderId: '17657594896',
    projectId: 'dolce-legado',
    authDomain: 'dolce-legado.firebaseapp.com',
    storageBucket: 'dolce-legado.firebasestorage.app',
  );
}
